### ISSUE TITLE
High Sierra permissions problem

### ISSUE THREAD

**Issue by keithdhd** [codeclan/laptop#11]
Permissions for /usr/local prevented one of the students with High Sierra OS from doing a brew update and continuing with the script. Couldn't change these permissions in the first instance.

**Comment by keithdhd** [comment]
It seems you can't change permissions on /usr/local. But you can change permissions on the folders BELOW /usr/local which looks like it does the job

**Comment by ajrussellaudio** [comment]
Seems to be a [known issue with Homebrew](https://github.com/Homebrew/brew/issues/3228)

Should we just add the Terminal commands from that issue to our Readme, and leave a long-term fox to them?

**Comment by abazlinton** [comment]
@keithdhd was this just an issue with that one student? Matt? He did have git installed independently and I think that was the issue in the end.

**Comment by keithdhd** [comment]
@abazlinton yeah it as only the one student

**Comment by abazlinton** [comment]
I'm gonna close this as I think it is an edge case which we can only really deal with in real time. I think some folders won't exist until the script creates them so I think a comprehensive fix for this doesn't have a good effort / reward ratio.
