### ISSUE TITLE
Script fails if Xcode doesn't install properly

### ISSUE THREAD

**Issue by waspyfaeleith** [codeclan/laptop#15]
On the last MYC (E20) the script was failing for a few students and it was found that, in most cases, this was due to XCode not being installed properly (there are `xcrun` errors in the logs)

Maybe we should show students how to read the logs and if they get the `xcrun` error then point them how to install the xcode command-line tools

```
xcode-select --install
```

**Comment by CraigMorton** [comment]
YEAP, always bloody happens. I've worked with Emz & Steph to improve the laptop info the students get once they're accepted onto the course. It now explains that Xcode must be installed and the licence agreement accepted before MYC.

So this **should** happen _slightly_ less going forward. However I think your idea is perfect for when it it inevitably comes up at every MYC cause people don't read instructions.

Should we maybe add your info to the MYC `.md` file in [instructor_resources](https://github.com/codeclan/instructor_resources)? That could help to keep all relevant info in the one place.

**Comment by abazlinton** [comment]
Are we sure we need Xcode? `xcode-select --install` is Xcode **tools**, not full Xcode. Normally the script will cause a popup to prompt for them to be installed...are they ignoring this, or are they not getting the prompt at all? (I've also seen students put in the wrong password 3 times)

The exception I've seen to this rule is students who have El Capitan. I've had to install older versions of mongo on these machines to get around a mandatory **full** Xcode install.

But students should not have El Capitan on their machines...in theory.

But perhaps I'm missing something? 

Also by now is there any reason we shouldn't mandate High Sierra? (it has the same system requirements as Sierra)

**Comment by waspyfaeleith** [comment]
I don't think they need Xcode, but they do need the xcode tools. If they don't install the them, then this will cause problems as some of the tools installed using brew depend on having the gcc compiler installed as brew downloads the sources and then builds them. This is only happening in some cases, but I think we need to show the students how to install them and point them to the logs, especially if we're getting them to run the script for themselves at home.

**Comment by CraigMorton** [comment]
To resolve this, we could:

1. Put `xcode-select --install` in the script at the very start. This really should ensure that the Xcode devtools have been installed before the rest of the script can run. It would also simplify instructions for fixing laptops that are not properly installed. "Run the script again" would solve a larger set of issues (those which require installing devtools).

2. Put `xcode-select --install` as an instruction on installation section of the README

**Comment by colin-riddell** [comment]
If Xcode tools are installed then the C toolchain binaries will be installed and available on path.
You could grep the output of `gcc` for `clang: error: no input files` indicating that it's installed, and `command not found: gcc` indicating that it's not installed.

**Comment by abazlinton** [comment]
Did #27 resolve this @CraigMorton ?

**Comment by CraigMorton** [comment]
This issue was resolved (hopefully!) in #27 

Went with a combination of Colin's `gcc` test on the exit code and my option 1. of forcing `xcode select --install` at the start of the script.

It uses `xcode select -p`'s exit code instead of `gcc` so even if someone has somehow installed `gcc` without installing the Apple Dev Tools the condition will still detect that dev tools is not installed / set up (AFAIK that shouldn't even be possible but 🤷‍♂️ )

Based on this condition it sticks the user in a while loop until they finish installing Dev Tools. Once they have it allows the rest of the script to continue.
