### ISSUE TITLE
Test macOS Mojave (10.14)

### ISSUE THREAD

**Issue by abazlinton** [codeclan/laptop#29]
It goes public Monday - 24/09/2018...

The public / developer beta is at gold master now.

E27 have MYC on 29/10/2018 so some of them might well have it. Plus any other students that update.

**Comment by CraigMorton** [comment]
Will update on a fresh laptop and test the script on Monday

**Comment by abazlinton** [comment]
All looking good. Script runs fine. Have been able to run all apps and this end code -

- `many_to_many_sinatra_zombies` from ruby
- `lab_full_stack_bucket_list` from JS
- `3_relationships_via_api_spring_data_rest_end` from java Spring

Should we close this @CraigMorton? (Did you say you were already running Mojave...?)

**Comment by colin-riddell** [comment]
All good? Should close?

**Comment by abazlinton** [comment]
Yeah I reckon.
