### ISSUE TITLE
Add postgres user - Spring compatibility

### ISSUE THREAD

**Issue by colin-riddell** [codeclan/laptop#36]
For all the Spring + Hibernate stuff we are using a `postgres` database user.

Add an additional postgres user called `posgres` using `createuser postgres`. This will make all labs and code-alongs for Spring compatible.

**Comment by abazlinton** [comment]
When I run `createuser postgres`  the user doesn't have the same role attributes as user. Could this cause issues? - 

> run `psql` in terminal
> run `\du` in psql shell

``` 
                               List of roles
 Role name |                         Attributes                         | Member of 
-----------+------------------------------------------------------------+-----------
 postgres  |                                                            | {}
 user      | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
```

**Comment by abazlinton** [comment]
Just tested `createuser postgres` and all worked. Presumably as this uses the `whoami` role to do the Create DB. So we'd need to keep `createdb "$(whoami)"` I think. Presumably all roles can read / write to the db...

**Comment by CraigMorton** [comment]
So it sounds like we might not need to do the superuser stuff at all? Even in the spring lessons where it's currently done. Is that would you found @abazlinton ?

We can add the `createuser postgres` line to the script easily. I'd like to confirm that we definitely don't need the superuser access first, if only to justify my figuring out how to grant superuser from the command line as at least potentially helpful.

We can make the `postgres` user a superuser within the script using this:

```
psql -f - << EOM
ALTER USER postgres WITH ROLE SUPERUSER;
EOM
```

This allows us to pass a "file" to `psql` to run on our DB which is then defined inline.

This will require the DB server to be up and running beforehand. And I don't think it does run immediately after a fresh install of postgres. We could maybe get it started with a `brew services restart postgresql` before creating & superuser-ing the new DB user.

**Comment by abazlinton** [comment]
Looks like you can also do
```
psql -c "ALTER USER postgres WITH Superuser;"
```
(`WITH ROLE` generates syntax error for me)

But not so keen on having have the script start postgres.  Feel like we should try and KISS.

So I think just add `createuser postgres`? Assuming we trust September me...haven't tested again.

**Comment by CraigMorton** [comment]
Oh yeah I got the same syntax error and pasted in the broken one, sorry! Yeah that's what I meant. Your one seems much nicer, just sending a command straight to the DB rather than my inline file nonsense.

I'll test just adding `createuser postgres` without altering the role
