### ISSUE TITLE
Add Disclaimer To README

### ISSUE THREAD

**Issue by waspyfaeleith** [codeclan/laptop#38]
Should we not have some kind of Disclaimer in the README (or somewhere) stating that running this script is at the user's own risk and that CodeClan takes no responsibility for data loss etc. 

After all, this is a public repo so anyone, anywhere could try running this script on their machines

**Comment by CraigMorton** [comment]
I would have thought that the MIT license should cover it.

Excerpt from license file with chunks removed for scan-ability: [full file here](https://github.com/codeclan/laptop/blob/master/LICENSE)
```
THE SOFTWARE IS PROVIDED ... WITHOUT WARRANTY ...
IN NO EVENT SHALL THE AUTHORS ... BE LIABLE FOR ANY CLAIM ...
ARISING FROM ... THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
```

**Comment by waspyfaeleith** [comment]
Cool
