### ISSUE TITLE
mongodb not installing with script

### ISSUE THREAD

**Issue by KJeffree** [codeclan/laptop#43]
mongodb is no longer installing with the script on any of the laptops, I think the process of installing it has changed. I found a solution by running the following commands:
brew tap mongodb/brew
brew install mongodb-community

**Comment by colin-riddell** [comment]
Good find.

I think we should future-proof ourselves from all of these mongodb and possibly postgres issues by having the script setup.

Thoughts welcome.

**Comment by colin-riddell** [comment]
Are the issues on  OS X 10.15 Catalina @KJeffree ?

**Comment by KJeffree** [comment]
Yes, we had one laptop with Catalina installed, and it also had the issue with installing mongodb

**Comment by harrisonbooth** [comment]
MongoDB changed their licensing so Homebrew had to change the way to install it to comply. So the script as it stands now is using the old method of installation. The installation shouldn't work on any OSX Version

**Comment by harrisonbooth** [comment]
My _guess_ would be that installing the `mongodb-community@4.2` would fix the Catalina issues - as when starting the brew service, I imagine it will try to update mongoDB using the old `mongodb` brew package, rather than the new `mongodb-community@4.2`. (This is speculation.)

**Comment by abazlinton** [comment]
If we want to keep starting `mongod` manually, Catalina does not let you create `/data/db` even with `sudo`. You can use this command to point it at the default settings - 

`mongod --config /usr/local/etc/mongod.conf`

But it doesn't start with logging. So we could -

`tail -f /usr/local/var/log/mongodb`

---
But the ideal setup is really this -

`brew services start mongodb-community`

As `mongod` should really be run as a background process like Postgres.

(more here: https://github.com/mongodb/homebrew-brew)
