### ISSUE TITLE
Notes on ARM Macs and Homebrew

### ISSUE THREAD

**Issue by abazlinton** [codeclan/laptop#57]
#### Notes on setting Terminal to "Open using Rosetta" for ARM Macs

Currently we require 'forcing' the Terminal into Intel mode with these instructions -

https://github.com/codeclan/laptop/blob/master/apple_silicon.md

So essentially the Terminal is ignorant to the fact that it's running on ARM, runs everything as Intel and Rosetta translates ARM > Intel. This is all fine. And the performance is still great. But it's a temporary solution as longer term the native ARM Homebrew will be good enough - status is here - https://github.com/Homebrew/brew/issues/7857. So at some point it will be safe to not "Open using Rosetta" and run the ARM Homebrew.

Additionally, even right now, ticking this box is quite 'belt and braces' in that a lot of stuff 'just works' without it being ticked. The Terminal will be in ARM mode, but can run an Intel executable where it needs too. This in some ways is preferable as I believe it makes it more likely that some applications work in ARM mode and you get better performance. I'm not 100% on this, but I think the OS applications / toolchains may have both versions bundled in the executables and so having the Terminal in ARM mode means you always get the optimum one run.

However, when I ran the laptop script without the box ticked Homebrew didnt play nice. So in the end the happy, if not optimal route was to have it ticked always. Though I think once the script is done, it may be safe to untick - more testing would be needed.

**Comment by Hazzard13** [comment]
I think your information here is actually quite out of date. As of Brew 3.0.0 (released early February), it's now recommended to just install the ARM version, and that error doesn't occur. 

In my experience, more packages are working natively on ARM than through Rosetta, although there are a few exceptions. Even that thread you've linked regarding status has gotten quite out of date. For example, openjdk has worked just fine for almost two months. To get a better idea of whether a package is natively supported via brew, refer to [brew.sh](https://brew.sh).

I'd recommend switching your terminal back to running normally, and installing brew from scratch. You may want to delete your old `/usr/local/homebrew` folder as well. As you say, if you need Rosetta brew for a specific package (I use it for Zookeeper, atm), just install brew under `sudo arch -x86_64`. It'll automatically install itself to `/usr/local/homebrew`, while the native version will install to `/opt/homebrew`. You can even make an alias for it, I use ibrew (Intel Brew).

**Comment by abazlinton** [comment]
Thanks @Hazzard13. It does appear things have moved on somewhat since I last looked at this.

One thing to bear in mind - CodeClan's fork of this script is designed for a specific set of users. Trying to be on the bleeding edge can cause more problems than it solves - especially for anyone maintaining it. 

Sometimes  - stability + simplicity + consistency between users  > perfectly up to date + optimal

**Comment by colin-riddell** [comment]
Great that you pointed those things out for us @Hazzard13 - some good observations and great tips - so thanks. As well as a couple of things that don't make sense.

Anyway - we LOVE that the future is aarch on darwin and we're  open to Aarch versions of the script if you'd like to PR? - but they'd also need to give good compatibility across the vast majority of older intel HW not to mention an array of different versions of OS. Let us knonw
